CREATE TABLE CONTACTS (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
mobile NUMBER(11) NOT NULL,
subject VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
message VARCHAR(150) NOT NULL,
PRIMARY KEY(id)
);